#!/usr/bin/env bash
# drop in replacement for mksrcinfo that has since been abandoned.
# Generates .SRCINFO files for use with Arch Linux AUR
# (aur.archlinux.org)
VER=8
OUTPUT='.SRCINFO'

if [ -f PKGBUILD ];then
  echo "# Generated by mksrcinfo(compatible) v${VER}" > "${OUTPUT}"
  echo "# $(date)" >> "${OUTPUT}"
  makepkg --printsrcinfo >> "${OUTPUT}"
 else
  echo "mksrcinfo: PKGBUILD doesn't exist"
  exit 1
fi
